### ISSUE TITLE
Change "invite link" in README

### ISSUE THREAD

**Issue by NicWebster96** [NicWebster96/gabe_bot#1]
to something like "I want gabe bot on my server" or something

simple issue to let someone practice PR and contributing :>

**Comment by dineshkumar12004** [comment]
can i work on this ? 
This is the URL i have to change right ?
![image](https://user-images.githubusercontent.com/67814205/124353384-d75b8f00-dc23-11eb-9817-679a4dd60905.png)

**Comment by NicWebster96** [comment]
@dineshkumar12004 Yes please feel free!
No I would like to change the text right above the red arrow that says "Invite Link". This discord bot is to be self-hosted, so there is no reason for the words "Invite Link" to appear in the README :)

Let me know if you have any other questions :)

**Comment by dineshkumar12004** [comment]
Made a PR :)
